/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignmentjava.Lucien;
import java.awt.event.WindowEvent;
import com.mycompany.assignmentjava.Utilites.FileManager;
import com.mycompany.assignmentjava.Utilites.FileManager.FileType;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class Top_up extends javax.swing.JFrame {
    static String ID;
    static String name;
    static String email;
    static String phone;
    static String role;
    static String balance;

    /**
     * Creates new form Top_up
     */
    public Top_up() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IDComboBox = new javax.swing.JComboBox<>();
        Balance_label = new javax.swing.JLabel();
        jButton_5RM = new javax.swing.JButton();
        jButton_10RM = new javax.swing.JButton();
        jButton_100RM = new javax.swing.JButton();
        jButton_250RM = new javax.swing.JButton();
        jButton_500RM = new javax.swing.JButton();
        jButton_1000RM = new javax.swing.JButton();
        jButton_20RM = new javax.swing.JButton();
        jButton_50RM = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nameText_CustomAmount = new javax.swing.JTextField();
        jButton_CustomRM = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2_CreateUser = new javax.swing.JMenuItem();
        jMenuItem3_updateUser = new javax.swing.JMenuItem();
        jMenuItem1_topUp = new javax.swing.JMenuItem();
        jMenuItem5_receipts = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu1.setText("✪ Users");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("🗹 ︎ Create ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("✅✘︎︎  Edi︎t & Delete");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("⫸ Options");

        jMenuItem4.setText("🞖 Logout ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        jLabel1.setText("Customer Top-up");

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel5.setLabelFor(IDComboBox);
        jLabel5.setText("UserID");

        IDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        IDComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDComboBoxActionPerformed(evt);
            }
        });

        Balance_label.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        Balance_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Balance_label.setText("RM 0");

        jButton_5RM.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton_5RM.setText("▲RM5");
        jButton_5RM.setActionCommand("RM50 ✅");
        jButton_5RM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_5RMActionPerformed(evt);
            }
        });

        jButton_10RM.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton_10RM.setText("▲RM10");
        jButton_10RM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_10RMActionPerformed(evt);
            }
        });

        jButton_100RM.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton_100RM.setText("▲RM100");
        jButton_100RM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_100RMActionPerformed(evt);
            }
        });

        jButton_250RM.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton_250RM.setText("▲RM250");
        jButton_250RM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_250RMActionPerformed(evt);
            }
        });

        jButton_500RM.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton_500RM.setText("▲RM500");
        jButton_500RM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_500RMActionPerformed(evt);
            }
        });

        jButton_1000RM.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton_1000RM.setText("▲RM1000");
        jButton_1000RM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1000RMActionPerformed(evt);
            }
        });

        jButton_20RM.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton_20RM.setText("▲RM20");
        jButton_20RM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_20RMActionPerformed(evt);
            }
        });

        jButton_50RM.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton_50RM.setText("▲RM50");
        jButton_50RM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_50RMActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 20)); // NOI18N
        jLabel3.setText("Custom Amount ");

        nameText_CustomAmount.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        jButton_CustomRM.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton_CustomRM.setText("Top-up");
        jButton_CustomRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CustomRMActionPerformed(evt);
            }
        });

        jMenu3.setText("✪ Users");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem2_CreateUser.setText("🗹 ︎ Create ");
        jMenuItem2_CreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2_CreateUserActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2_CreateUser);

        jMenuItem3_updateUser.setText("✅✘︎︎  Edi︎t & Delete");
        jMenuItem3_updateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3_updateUserActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3_updateUser);

        jMenuItem1_topUp.setText("▲ Top-up");
        jMenuItem1_topUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_topUpActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1_topUp);

        jMenuItem5_receipts.setText("✉ Send Receipts");
        jMenuItem5_receipts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5_receiptsActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5_receipts);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("⫸ Options");

        jMenuItem5.setText("🞖 Logout ");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(Balance_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(94, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton_5RM, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton_10RM, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton_100RM, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton_250RM, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton_500RM, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton_1000RM, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton_20RM, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton_50RM, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nameText_CustomAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_CustomRM, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(IDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(Balance_label, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_5RM, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_100RM, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_20RM, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_50RM, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_10RM, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_1000RM, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_500RM, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_250RM, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameText_CustomAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_CustomRM, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        List<String> records = FileManager.getAllRecords(FileManager.FileType.USERS);
        List<String> displayRecords = new ArrayList<>();

        for (String record : records) {
            String[] parts = record.split(FileManager.DELIMITER);
            // Ensure there are enough parts to display name, ID, and email.
            if (parts.length >= 6) {
                ID = parts[0];
                name = parts[1];
                email = parts[2];
                role = parts[5];
                phone = parts[3];
                //        balance = parts[8]; //ucomment this later on
                Balance_label.setText("RM "+ phone); //change this to
                // Only add the record if the role is "customer"
                if (role.equalsIgnoreCase("customer")) {
                    displayRecords.add(name + " (" + ID + ") - " + email + " (" + role.toUpperCase() + ")");
                }
            } else {
                // If the record doesn't match the expected format, add the raw record.
                displayRecords.add(record);
            }
        }

        // Set the combo box model with the human-readable items
        IDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
            displayRecords.toArray(new String[0])
        ));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        new CreateCustomer().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        new UserUpdateDetails().setVisible(true);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void IDComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDComboBoxActionPerformed
        // TODO add your handling code here:

        String selectedUser = (String) IDComboBox.getSelectedItem();

        if (selectedUser != null && selectedUser.contains("(") && selectedUser.contains(")")) {
            // Extract the user ID from the format: "Zakwan (75250626) - Zakwan@goodboy.com (CUSTOMER)"
            int start = selectedUser.indexOf("(") + 1;
            int end = selectedUser.indexOf(")");
            String extractedID = selectedUser.substring(start, end).trim();

            // Search for the full record using the extracted ID
            List<String> userDetails = FileManager.searchRecords(FileManager.FileType.USERS, "userID", extractedID);

            if (!userDetails.isEmpty()) {
                // Split the record into fields
                String[] parts = userDetails.get(0).split(FileManager.DELIMITER);

                if (parts.length >= 6) { // Ensure there are enough fields before accessing them
                    String userID = parts[0];
                    Top_up.name = parts[1];
                    Top_up.phone = parts[3]; // wil be used instead of balance for now
//                    Top_up.balance = parts[8];      
                    Top_up.role = parts[5];
                    Top_up.ID = userID;
                    //        balance = parts[8]; //ucomment this later on
                      Balance_label.setText("RM "+ phone); //change this to 
                } else {
                    System.out.println("Invalid user record format.");
                }
            } else {
                System.out.println("User not found.");
            }
        }
    }//GEN-LAST:event_IDComboBoxActionPerformed

    private void jButton_5RMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_5RMActionPerformed
    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to top-up RM5?",
            "Confirm Top-Up",
            JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        updateCustomerBalance(5);
    }
    }//GEN-LAST:event_jButton_5RMActionPerformed

    private void jButton_10RMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_10RMActionPerformed
        // TODO add your handling code here:
            int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to top-up RM10?",
            "Confirm Top-Up",
            JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        updateCustomerBalance(10);
    }
    }//GEN-LAST:event_jButton_10RMActionPerformed

    private void jButton_100RMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_100RMActionPerformed
        // TODO add your handling code here:
            int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to top-up RM100?",
            "Confirm Top-Up",
            JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        updateCustomerBalance(100);
    }
    }//GEN-LAST:event_jButton_100RMActionPerformed

    private void jButton_250RMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_250RMActionPerformed
        // TODO add your handling code here:
            int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to top-up RM250?",
            "Confirm Top-Up",
            JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        updateCustomerBalance(250);
    }
    }//GEN-LAST:event_jButton_250RMActionPerformed

    private void jButton_500RMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_500RMActionPerformed
        // TODO add your handling code here:
            int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to top-up RM500?",
            "Confirm Top-Up",
            JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        updateCustomerBalance(500);
    }
    }//GEN-LAST:event_jButton_500RMActionPerformed

    private void jButton_1000RMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1000RMActionPerformed
        // TODO add your handling code here:
            int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to top-up RM1000?",
            "Confirm Top-Up",
            JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        updateCustomerBalance(1000);
    }
    }//GEN-LAST:event_jButton_1000RMActionPerformed

    private void jButton_20RMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_20RMActionPerformed
        // TODO add your handling code here:
            int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to top-up RM20?",
            "Confirm Top-Up",
            JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        updateCustomerBalance(20);
    }
    }//GEN-LAST:event_jButton_20RMActionPerformed

    private void jButton_50RMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_50RMActionPerformed
        // TODO add your handling code here:
          int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to top-up RM50?",
            "Confirm Top-Up",
            JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        updateCustomerBalance(50);
    }
    }//GEN-LAST:event_jButton_50RMActionPerformed

    private void updateCustomerBalance(double amount) {
    // Check if a customer is selected
    if (Top_up.ID == null || Top_up.ID.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No customer selected!");
        return;
    }
    
    // Call the Admin method to update the balance (using phone as a placeholder for balance)
    boolean success = Admin.updateCustomerBalance(Top_up.ID, amount);
    
    if (success) {
        // Re-fetch the updated record for the user from the file.
        List<String> records = FileManager.searchRecords(FileManager.FileType.USERS, "userID", Top_up.ID);
        if (!records.isEmpty()) {
            String updatedRecord = records.get(0);
            String[] parts = updatedRecord.split(FileManager.DELIMITER);
            // Assuming the balance is stored in the phone field (index 3)
            try {
                double updatedBalance = Double.parseDouble(parts[3]);
                Balance_label.setText("RM " + updatedBalance);
            } catch (NumberFormatException e) {
                Balance_label.setText("Invalid Balance");
            }
        } else {
            Balance_label.setText("Record not found");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Failed to update balance.");
    }
}
    private void jButton_CustomRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CustomRMActionPerformed
            String amountStr = nameText_CustomAmount.getText().trim();
    if (amountStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter an amount.");
        return;
    }
    
    try {
        double amount = Double.parseDouble(amountStr);
        updateCustomerBalance(amount);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Please enter a valid number for the amount!");
    }
    }//GEN-LAST:event_jButton_CustomRMActionPerformed

    private void jMenuItem2_CreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2_CreateUserActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new CreateCustomer().setVisible(true);
    }//GEN-LAST:event_jMenuItem2_CreateUserActionPerformed

    private void jMenuItem3_updateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3_updateUserActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new UserUpdateDetails().setVisible(true);
    }//GEN-LAST:event_jMenuItem3_updateUserActionPerformed

    private void jMenuItem1_topUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_topUpActionPerformed
        // open top-up
        this.dispose();
        new Top_up().setVisible(true);
    }//GEN-LAST:event_jMenuItem1_topUpActionPerformed

    private void jMenuItem5_receiptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5_receiptsActionPerformed
        // Dispose the current frame
        this.dispose();
        // Create and show a new instance of send_receipts
        new send_receipts().setVisible(true);

    }//GEN-LAST:event_jMenuItem5_receiptsActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Top_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Top_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Top_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Top_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Top_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Balance_label;
    private javax.swing.JComboBox<String> IDComboBox;
    private javax.swing.JButton jButton_1000RM;
    private javax.swing.JButton jButton_100RM;
    private javax.swing.JButton jButton_10RM;
    private javax.swing.JButton jButton_20RM;
    private javax.swing.JButton jButton_250RM;
    private javax.swing.JButton jButton_500RM;
    private javax.swing.JButton jButton_50RM;
    private javax.swing.JButton jButton_5RM;
    private javax.swing.JButton jButton_CustomRM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1_topUp;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem2_CreateUser;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem3_updateUser;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem5_receipts;
    private javax.swing.JTextField nameText_CustomAmount;
    // End of variables declaration//GEN-END:variables
}
