/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignmentjava.Shariq.UI;

import com.mycompany.assignmentjava.Shariq.Classes.Manager;
import com.mycompany.assignmentjava.Utilites.FileManager;
import javax.swing.JOptionPane;

/**
 *
 * @author ysssh
 */
public class ManagerHomeJFrame extends javax.swing.JFrame {
    
    Manager manager;

    /**
     * Creates new form ManagerHomeJFrame
     * @param manager
     * @param userDetails
     */
    public ManagerHomeJFrame(Manager manager){
        initComponents();
        this.manager = manager;
    }
    
    public ManagerHomeJFrame(){
        initComponents();
    }
    
//    public ManagerHomeJFrame(String[] userDetails) {
//        initComponents();
//        //Initiate Manager
//       //TODO: Standardize this later
//        Manager manager = new Manager(userDetails[1], userDetails[2], userDetails[3], userDetails[4]);
//        this.manager = manager;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVendorPerformance = new javax.swing.JButton();
        btnRunnerPerformance = new javax.swing.JButton();
        btnVendorListings = new javax.swing.JButton();
        btnCustomerComplaints = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Manager Home");

        btnVendorPerformance.setText("Monitor Vendor Performance");
        btnVendorPerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendorPerformanceActionPerformed(evt);
            }
        });

        btnRunnerPerformance.setText("Monitor Runner Performance");
        btnRunnerPerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunnerPerformanceActionPerformed(evt);
            }
        });

        btnVendorListings.setText("Manage Vendor Listings");
        btnVendorListings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendorListingsActionPerformed(evt);
            }
        });

        btnCustomerComplaints.setText("Manage Customer Complaints");
        btnCustomerComplaints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerComplaintsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnVendorPerformance)
                        .addGap(41, 41, 41)
                        .addComponent(btnRunnerPerformance)
                        .addGap(49, 49, 49)
                        .addComponent(btnVendorListings)
                        .addGap(45, 45, 45)
                        .addComponent(btnCustomerComplaints))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVendorPerformance)
                    .addComponent(btnRunnerPerformance)
                    .addComponent(btnVendorListings)
                    .addComponent(btnCustomerComplaints))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVendorPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendorPerformanceActionPerformed
        manager.monitorVendorPerformance.launchJFrame();
    }//GEN-LAST:event_btnVendorPerformanceActionPerformed

    private void btnRunnerPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunnerPerformanceActionPerformed
        //manager.monitorRunnerPerformance();
    }//GEN-LAST:event_btnRunnerPerformanceActionPerformed

    private void btnVendorListingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendorListingsActionPerformed
        //manager.manageVendorListings();
    }//GEN-LAST:event_btnVendorListingsActionPerformed

    private void btnCustomerComplaintsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerComplaintsActionPerformed
        //manager.manageCustomerComplaints();
    }//GEN-LAST:event_btnCustomerComplaintsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerHomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerHomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerHomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerHomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerHomeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerComplaints;
    private javax.swing.JButton btnRunnerPerformance;
    private javax.swing.JButton btnVendorListings;
    private javax.swing.JButton btnVendorPerformance;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
